### ISSUE TITLE
Crash on video playback v1.2 OpenBSD/amd64

### ISSUE THREAD

**Issue by mulander** [baedert/corebird#515]
ERROR:widgets/MediaVideoWidget.c:1055:__lambda84_: assertion failed: (app_src != null)

Clicking 'play' on [this tweet](https://twitter.com/gamejolt/status/704739797915447296) leads to a corebird v1.2 crash on OpenBSD amd64

This issue was not present in corebird v1.1 (or I had huge luck with picking video tweets)

```
$ pkg_info -Q plugins-bad
gstreamer-plugins-bad-0.10.23p22
gstreamer1-plugins-bad-1.6.3 (installed)
```

```
$ corebird                                                                                         

(corebird:6380): Gtk-WARNING **: Theme parsing error: style.css:151:12: 'min-height' is not a valid property name

(corebird:6380): Gtk-WARNING **: Theme parsing error: style.css:225:12: 'min-height' is not a valid property name

(corebird:6380): Gtk-WARNING **: Theme parsing error: style.css:226:11: 'min-width' is not a valid property name

(corebird:6380): GLib-GObject-CRITICAL **: g_object_get: assertion 'G_IS_OBJECT (object)' failed

** (corebird:6380): WARNING **: Utils.vala:442: No resolution found in url 'https://pbs.twimg.com/tweet_video/Cce9DicWAAYue6g.mp4'

** (corebird:6380): CRITICAL **: MediaVideoWidget.vala:128: Could not create a gtksink. Need gst-plugins-bad >= 1.6
**
ERROR:widgets/MediaVideoWidget.c:1055:__lambda84_: assertion failed: (app_src != null)
Abort trap (core dumped) 
```

```
(gdb) bt
#0  0x00000a89e397187a in thrkill () at <stdin>:2
#1  0x00000a89e396cf39 in *_libc_abort () at /usr/src/lib/libc/stdlib/abort.c:52
#2  0x00000a89a50d1872 in g_assertion_message () from /usr/local/lib/libglib-2.0.so.4200.2
#3  0x00000a89a50d1d7f in g_assertion_message_expr () from /usr/local/lib/libglib-2.0.so.4200.2
#4  0x00000a87836a5d12 in dm_thread_load_avatar () from /usr/local/bin/corebird
#5  0x00000a8a76ae32c3 in g_closure_invoke () from /usr/local/lib/libgobject-2.0.so.4200.2
#6  0x00000a8a76af993f in signal_emit_unlocked_R () from /usr/local/lib/libgobject-2.0.so.4200.2
#7  0x00000a8a76afbeb9 in g_signal_emit_valist () from /usr/local/lib/libgobject-2.0.so.4200.2
#8  0x00000a8a76afc681 in g_signal_emit () from /usr/local/lib/libgobject-2.0.so.4200.2
#9  0x00000a8a3229e01e in io_read () from /usr/local/lib/libsoup-2.4.so.8.3
#10 0x00000a8a3229e1c5 in io_run_until () from /usr/local/lib/libsoup-2.4.so.8.3
#11 0x00000a8a3229f055 in io_run () from /usr/local/lib/libsoup-2.4.so.8.3
#12 0x00000a8a3229f39b in io_run_ready () from /usr/local/lib/libsoup-2.4.so.8.3
#13 0x00000a89a50ad452 in g_main_context_dispatch () from /usr/local/lib/libglib-2.0.so.4200.2
#14 0x00000a89a50af5db in g_main_context_iterate () from /usr/local/lib/libglib-2.0.so.4200.2
#15 0x00000a89a50af6a7 in g_main_context_iteration () from /usr/local/lib/libglib-2.0.so.4200.2
#16 0x00000a89d6bef2b2 in g_application_run () from /usr/local/lib/libgio-2.0.so.4200.2
#17 0x00000a8783617ebb in __register_frame_info () from /usr/local/bin/corebird
#18 0x00000a8783617c31 in ?? () from /usr/local/bin/corebird
#19 0x0000000000000000 in ?? ()
Current language:  auto; currently asm
```

I also reproduced this issue on a @securitay tweet

```
** (corebird:9219): WARNING **: Utils.vala:442: No resolution found in url 'https://pbs.twimg.com/tweet_video/CcewOK9UAAEN1Pk.mp4'

** (corebird:9219): CRITICAL **: MediaVideoWidget.vala:128: Could not create a gtksink. Need gst-plugins-bad >= 1.6
**
ERROR:widgets/MediaVideoWidget.c:1055:__lambda84_: assertion failed: (app_src != null)
```

**Comment by mulander** [comment]
Works on v1.1 with the same tweet as linked in the original report.

```
$ corebird                                                                                                                                               

** (corebird:6308): WARNING **: Utils.vala:66: Image file '/home/mulander/.cache/corebird/assets/media/thumbs/704739797915447296_21501266_0.png' contains no data

** (corebird:6308): WARNING **: InlineMediaDownloader.vala:175: 'http://twitter.com/gamejolt/status/704739797915447296/photo/1` couldn't be loaded from disk.

** (corebird:6308): WARNING **: InlineMediaDownloader.vala:286: http://twitter.com/gamejolt/status/704739797915447296/photo/1: Unrecognized image file format
```

**Comment by mulander** [comment]
This issue was related to how we built multimedia/gstreamer1/plugins-bad. Corebird v1.2 no longer crashes after gtksink support has been enabled in the port.
